### PR TITLE
Setup code coverage and travis

### PR DESCRIPTION
**Pull request by mxstbr**
@Noviny a test was failing for me locally, do you have any idea why it could not be working? Getting an error "Could not find engine (txt)."

### CODE REVIEW

**Comment by mxstbr** [comment]
Travis is erroring because `"Error: Could not load transport (Mandrill)"`. Any ideas?

**Comment by mxstbr** [comment]
@Noviny Travis is failing because "Error: Could not load transport (Mandrill)" (and Mailgun) - any idea how to fix that?

**Comment by mxstbr** [comment]
This is still failing due to "Error: Could not load transport (mandrill)" on Node 0.12 – any ideas what's happening here Jed? We should _really_ get this merged.

**Comment by mxstbr** [comment]
Yessss 🚢

**Comment by JedWatson** [comment]
:tada:

**Pull request merged**
